namespace Denapoli.Modules.Payment
{
    public static class Const
    {
        public const byte ENQ = 0x05;
        public const byte ACK = 0x06;
        public const byte NAK = 0x15;
        public const byte STX = 0x02;
        public const byte ETX = 0x03;
        public const byte ETB = 0x17;
        public const byte EOT = 0x04;
        public const byte DLE = 0x10;

        public static string[] Diag = new[]
                                          {
                                              "Solvabilité acceptée",
                                              "APPLICATION NON INITIALISEE",
                                              "APPLICATION NON ACTIVE",
                                              "CLASSE NON GEREE",
                                              "NOYAU NON V52",
                                              "CARTE NON TRAITEE",
                                              "",
                                              "",
                                              "",
                                              "MONTANT MAX CARTE ETRANGERE DEPASSE",
                                              "MODE NON GEREE",
                                              "PROBLEME INTEGRITE DU FICHIER TRANSACTION",
                                              "FICHIER TRANSACTION PLEIN",
                                              "MONTANT MAX DEPASSE",
                                              "MONTANT MIN NONATTEINT",
                                              "MONTANT NUL",
                                              "",
                                              "MONNAIE NON GEREE",
                                              "MONNAIE CARTE NON GEREE",
                                              "BIN DE LA CARTE ABSENT DE LA TABLE DES BIN",
                                              "CARTE REFUSEE DANS LA LISTE DE CONTRÔLE",
                                              "BIN DE LA CARTE REFUSEE",
                                              "CARTE PERIMEE",
                                              "CARTE NON VALIDE",
                                              "PROBLEME CODE TRAITEMENT CARTE",
                                              "PROBLEME CODE SERVICE CARTE",
                                              "CARTE REFUSEE EN AUTORISATION",
                                              "LONGUEUR DU NO PORTEUR INCORRECTE",
                                              "DUREE DE VALIDITE DEPASSEE",
                                              "BIN DE LA CARTE SURVEILLE DANS LA TABLE DES BIN",
                                              "CARTE SURVEILLEE DANS LA LISTE DE CONTROLE",
                                              "CARTE BLOQUEE",
                                              "DONNEE CARTE INCOHERENTE",
                                              "PROBLEME VA_VS",
                                              "PROBLEME CALCUL CAI EMETTEUR",
                                              "PROBLEME CONTROL DE FLUX",
                                              "PROBLEME CALCUL CAI ACQUEREUR",
                                              "ABANDON SUR INTRODUIRE CARTE",
                                              "PROBLEME CONSOLIDATION EXTERNE",
                                              "ANNULATION OU ABANDON SUR SAISIE CODE",
                                              "ABANDON APRES SAISIE D'UN CODE FAUX",
                                              "ABANDON APRES SAISIE DE DEUX CODE FAUX",
                                              "SAISIE DE TROIS FAUX",
                                              "PORTEUR ABSENT A LA SAISIE DU CODE",
                                              "TIME-OUT SAISIE DU CODE",
                                              "TYPE DE TRANSACTION REFUSE",
                                              "PROBLEME COHERENCE MODE DE FONCTIONNEMENT ET CODE TRAITEMENT",
                                              "RECU NON DISPONIBLE",
                                              "INCIDENT TECHNIQUE CARTE",
                                              "PAS DE SOLVABILITE AU PREALABLE",
                                              "MONTANT ENREGISTREMENT DIFFERENT MONTANT SOLVABILITE",
                                              "",
                                              "PROBLEME DE LIAISON AU CENTRE D'AUTORISATION",
                                              "CARTE INTERDITE DANS LE FICHIER TRANSACTION",
                                              "BIN DE LA CARTE INTERDIT DANS LA TABLE DES BIN",
                                              "CARTE INTERDITE DANS LA LISTE DE CONTRÔLE",
                                              "CARTE INTERDITE PAR LE CENTRE D'AUTORISATION",
                                              "SAM HORS SERVICE",
                                              "DEFAULT SAM",
                                              "SAM INVALIDE",
                                              "SAM NON UTILISABLE",
                                              "SAM PERIME",
                                              "SAM ECHANGE",
                                              "PME CHARGER BORNE",
                                              "PME SOLDE INSUFFISANT",
                                              "PME BLOQUE",
                                              "PME INVALIDE",
                                              "PME DEBIT PROBABLE",
                                              "PME ANNULATION OK",
                                              "PME ANNULATION KO",
                                              "OCL A PEAGE VERROUILLE",
                                              "",
                                              "",
                                              "",
                                              "",
                                              "",
                                              "",
                                              "",
                                              "",
                                              "CUMUL LAT DEPASSE",
                                              "MODULE EMVDC NON CHARGE",
                                              "ABANDON SUR CHOIX (TICKET, LANGUE)",
                                              "CARTE INTERDITE DANS LE FICHIER TRANSACTION",
                                              "CARTE REFUSEE DANS LE FICHIER TRANSACTION",
                                              "PROBLEME FORMAT CARTE",
                                              "EMV ECHEC INITIATE APPLICATION PROCESSING",
                                              "EMV INITIATE APPLICATION PROCESSING EASY ENTRY ECHEC",
                                              "EMV APPLICATION SELECTION ECHEC",
                                              "EMV READ APPLICATION DATA ECHEC",
                                              "EMV PROCESSING RESTRICTION ECHEC",
                                              "EMV OFFLINE DATA AUTHENTIFICATION ECHEC",
                                              "EMV ECHEC CONTROL DU CODE",
                                              "EMV TERMINAL RISK MANAGEMENT ECHEC",
                                              "EMV TERMINAL ACTION ANALYSIS ECHEC",
                                              "EMV CARD REFUS (Refus (AAC) sur Generate AC)",
                                              "EMV CARD ACTION ANALYSIS ECHEC",
                                              "EMV ON LINE PROCESSING ECHEC",
                                              "EMV COMPLETION ECHEC",
                                              "EMV SCRIPT PROCESSING 1 ECHEC",
                                              "EMV SCRIPT PROCESSING 2 ECHEC"
                                          };
    }
}